#pragma once

// Generated by MaM 6/tools/gen_mm6_lstr.py, do not edit.

#include <array>

/**
 * MM6 global.txt index for each MM7 `LstrId`, or -1 with a fallback text if MM6 has no such string. Fallbacks are
 * the Czech MM7 texts in cp1250.
 */
struct Mm6LstrEntry {
    int mm6Index;
    const char *fallback;
};

inline constexpr std::array<Mm6LstrEntry, 677> mm6LstrTable = {{
    {0, nullptr}, // 0
    {1, nullptr}, // 1
    {-1, "\310ern\375 ryt\355\370"}, // 2
    {-1, "Zv\354d"}, // 3
    {4, nullptr}, // 4
    {5, nullptr}, // 5
    {6, nullptr}, // 6
    {7, nullptr}, // 7
    {8, nullptr}, // 8
    {9, nullptr}, // 9
    {10, nullptr}, // 10
    {11, nullptr}, // 11
    {12, nullptr}, // 12
    {-1, "Vrah"}, // 13
    {14, nullptr}, // 14
    {15, nullptr}, // 15
    {16, nullptr}, // 16
    {17, nullptr}, // 17
    {18, nullptr}, // 18
    {19, nullptr}, // 19
    {20, nullptr}, // 20
    {-1, "Mnich"}, // 21
    {22, nullptr}, // 22
    {23, nullptr}, // 23
    {-1, "Odolnost proti ohni"}, // 24
    {25, nullptr}, // 25
    {-1, "Zasv\354cenec"}, // 26
    {-1, "Ninja"}, // 27
    {-1, "Zloduch"}, // 28
    {29, nullptr}, // 29
    {30, nullptr}, // 30
    {-1, "Hrani\350\341\370"}, // 31
    {32, nullptr}, // 32
    {-1, "P\341n hrani\350\341\370\371"}, // 33
    {34, nullptr}, // 34
    {35, nullptr}, // 35
    {36, nullptr}, // 36
    {-1, "Celkov\375 \350as:"}, // 37
    {38, nullptr}, // 38
    {39, nullptr}, // 39
    {-1, "Lovec odm\354n"}, // 40
    {41, nullptr}, // 41
    {42, nullptr}, // 42
    {43, nullptr}, // 43
    {-1, "Kn\354z Sv\354tla"}, // 44
    {45, nullptr}, // 45
    {-1, "Kn\354z Temnoty"}, // 46
    {47, nullptr}, // 47
    {-1, "\310ernokn\354\236n\355k"}, // 48
    {-1, "Lich"}, // 49
    {-1, "Uh\375b\341n\355"}, // 50
    {51, nullptr}, // 51
    {52, nullptr}, // 52
    {53, nullptr}, // 53
    {54, nullptr}, // 54
    {55, nullptr}, // 55
    {56, nullptr}, // 56
    {57, nullptr}, // 57
    {58, nullptr}, // 58
    {59, nullptr}, // 59
    {60, nullptr}, // 60
    {61, nullptr}, // 61
    {62, nullptr}, // 62
    {63, nullptr}, // 63
    {64, nullptr}, // 64
    {65, nullptr}, // 65
    {66, nullptr}, // 66
    {67, nullptr}, // 67
    {68, nullptr}, // 68
    {69, nullptr}, // 69
    {70, nullptr}, // 70
    {71, nullptr}, // 71
    {72, nullptr}, // 72
    {73, nullptr}, // 73
    {74, nullptr}, // 74
    {75, nullptr}, // 75
    {76, nullptr}, // 76
    {-1, "Beze zbran\354"}, // 77
    {78, nullptr}, // 78
    {79, nullptr}, // 79
    {80, nullptr}, // 80
    {81, nullptr}, // 81
    {82, nullptr}, // 82
    {83, nullptr}, // 83
    {84, nullptr}, // 84
    {85, nullptr}, // 85
    {86, nullptr}, // 86
    {87, nullptr}, // 87
    {-1, "Ident. nestv\371r"}, // 88
    {318, nullptr}, // 89
    {-1, "Kraden\355"}, // 90
    {91, nullptr}, // 91
    {92, nullptr}, // 92
    {93, nullptr}, // 93
    {94, nullptr}, // 94
    {-1, "Alchymie"}, // 95
    {-1, "Velmistr"}, // 96
    {97, nullptr}, // 97
    {98, nullptr}, // 98
    {-1, "\310lov\354k"}, // 99
    {100, nullptr}, // 100
    {-1, "Trpasl\355k"}, // 101
    {102, nullptr}, // 102
    {-1, "Elf"}, // 103
    {104, nullptr}, // 104
    {105, nullptr}, // 105
    {-1, "Goblin"}, // 106
    {107, nullptr}, // 107
    {108, nullptr}, // 108
    {109, nullptr}, // 109
    {110, nullptr}, // 110
    {-1, "Velmistr"}, // 111
    {112, nullptr}, // 112
    {113, nullptr}, // 113
    {-1, "Lupi\350"}, // 114
    {115, nullptr}, // 115
    {116, nullptr}, // 116
    {117, nullptr}, // 117
    {118, nullptr}, // 118
    {-1, "Lu\350i\232tnick\375 mistr"}, // 119
    {120, nullptr}, // 120
    {121, nullptr}, // 121
    {122, nullptr}, // 122
    {123, nullptr}, // 123
    {-1, "Ost\370elova\350"}, // 124
    {125, nullptr}, // 125
    {126, nullptr}, // 126
    {-1, "Bez textu!"}, // 127
    {128, nullptr}, // 128
    {129, nullptr}, // 129
    {-1, "Hr\341\350"}, // 130
    {131, nullptr}, // 131
    {132, nullptr}, // 132
    {133, nullptr}, // 133
    {539, nullptr}, // 134
    {135, nullptr}, // 135
    {136, nullptr}, // 136
    {137, nullptr}, // 137
    {138, nullptr}, // 138
    {139, nullptr}, // 139
    {140, nullptr}, // 140
    {141, nullptr}, // 141
    {142, nullptr}, // 142
    {143, nullptr}, // 143
    {144, nullptr}, // 144
    {145, nullptr}, // 145
    {146, nullptr}, // 146
    {147, nullptr}, // 147
    {148, nullptr}, // 148
    {149, nullptr}, // 149
    {150, nullptr}, // 150
    {151, nullptr}, // 151
    {543, nullptr}, // 152
    {153, nullptr}, // 153
    {154, nullptr}, // 154
    {155, nullptr}, // 155
    {156, nullptr}, // 156
    {157, nullptr}, // 157
    {158, nullptr}, // 158
    {120, nullptr}, // 159
    {535, nullptr}, // 160
    {-1, "Ukr\341st"}, // 161
    {162, nullptr}, // 162
    {163, nullptr}, // 163
    {164, nullptr}, // 164
    {165, nullptr}, // 165
    {166, nullptr}, // 166
    {167, nullptr}, // 167
    {168, nullptr}, // 168
    {169, nullptr}, // 169
    {170, nullptr}, // 170
    {171, nullptr}, // 171
    {172, nullptr}, // 172
    {173, nullptr}, // 173
    {174, nullptr}, // 174
    {175, nullptr}, // 175
    {176, nullptr}, // 176
    {33, nullptr}, // 177
    {178, nullptr}, // 178
    {179, nullptr}, // 179
    {180, nullptr}, // 180
    {-1, "Ukr\341st %24"}, // 181
    {182, nullptr}, // 182
    {183, nullptr}, // 183
    {184, nullptr}, // 184
    {-1, "Kraden\341 v\354c"}, // 185
    {525, nullptr}, // 186
    {-1, "Ukradeno"}, // 187
    {188, nullptr}, // 188
    {189, nullptr}, // 189
    {190, nullptr}, // 190
    {-1, "Byli jste vyhozeni z tohoto obchodu!"}, // 191
    {192, nullptr}, // 192
    {193, nullptr}, // 193
    {-1, "Odolnost proti vod\354"}, // 194
    {195, nullptr}, // 195
    {196, nullptr}, // 196
    {197, nullptr}, // 197
    {198, nullptr}, // 198
    {199, nullptr}, // 199
    {200, nullptr}, // 200
    {201, nullptr}, // 201
    {-1, "Odolnost proti vzduchu"}, // 202
    {203, nullptr}, // 203
    {-1, "Odolnost proti t\354lu"}, // 204
    {205, nullptr}, // 205
    {206, nullptr}, // 206
    {207, nullptr}, // 207
    {-1, "Odolnost proti zemi"}, // 208
    {209, nullptr}, // 209
    {210, nullptr}, // 210
    {211, nullptr}, // 211
    {212, nullptr}, // 212
    {-1, "Odolnost proti mysli"}, // 213
    {214, nullptr}, // 214
    {-1, "Zjisti \236ivot"}, // 215
    {216, nullptr}, // 216
    {-1, "Neviditelnost"}, // 217
    {-1, "Ob\354tov\341n\355"}, // 218
    {-1, "Den boh\371"}, // 219
    {220, nullptr}, // 220
    {-1, "Osud"}, // 221
    {222, nullptr}, // 222
    {-1, ""}, // 223
    {-1, ""}, // 224
    {-1, "Velmistr"}, // 225
    {-1, "Nastaven\355 Gamma relativn\354 \"zjasn\355\" hru. Z\341vis\355 to tak\351 na tv\351m monitoru."}, // 226
    {227, nullptr}, // 227
    {-1, "Kladivov\351 p\354sti"}, // 228
    {-1, "Odr\341\236en\355 bolesti"}, // 229
    {230, nullptr}, // 230
    {231, nullptr}, // 231
    {232, nullptr}, // 232
    {-1, "Ochrana"}, // 233
    {-1, "Regenerace"}, // 234
    {-1, "Do\350asn\354 P\370esnost"}, // 235
    {236, nullptr}, // 236
    {237, nullptr}, // 237
    {238, nullptr}, // 238
    {239, nullptr}, // 239
    {240, nullptr}, // 240
    {241, nullptr}, // 241
    {242, nullptr}, // 242
    {243, nullptr}, // 243
    {244, nullptr}, // 244
    {245, nullptr}, // 245
    {-1, "Do\350asn\354 Odolnost"}, // 246
    {-1, "Do\350asn\354 Inteligence"}, // 247
    {-1, "Do\350asn\354 \212t\354st\355"}, // 248
    {-1, "Do\350asn\354 Osobnost"}, // 249
    {250, nullptr}, // 250
    {251, nullptr}, // 251
    {252, nullptr}, // 252
    {253, nullptr}, // 253
    {254, nullptr}, // 254
    {255, nullptr}, // 255
    {256, nullptr}, // 256
    {257, nullptr}, // 257
    {-1, "Do\350asn\354 Rychlost"}, // 258
    {259, nullptr}, // 259
    {260, nullptr}, // 260
    {261, nullptr}, // 261
    {262, nullptr}, // 262
    {263, nullptr}, // 263
    {264, nullptr}, // 264
    {265, nullptr}, // 265
    {-1, "ZAHOZEN\315 KARTY"}, // 266
    {267, nullptr}, // 267
    {268, nullptr}, // 268
    {269, nullptr}, // 269
    {270, nullptr}, // 270
    {271, nullptr}, // 271
    {272, nullptr}, // 272
    {273, nullptr}, // 273
    {274, nullptr}, // 274
    {275, nullptr}, // 275
    {276, nullptr}, // 276
    {277, nullptr}, // 277
    {278, nullptr}, // 278
    {279, nullptr}, // 279
    {280, nullptr}, // 280
    {281, nullptr}, // 281
    {282, nullptr}, // 282
    {283, nullptr}, // 283
    {284, nullptr}, // 284
    {285, nullptr}, // 285
    {286, nullptr}, // 286
    {287, nullptr}, // 287
    {288, nullptr}, // 288
    {289, nullptr}, // 289
    {290, nullptr}, // 290
    {291, nullptr}, // 291
    {292, nullptr}, // 292
    {293, nullptr}, // 293
    {294, nullptr}, // 294
    {295, nullptr}, // 295
    {296, nullptr}, // 296
    {297, nullptr}, // 297
    {298, nullptr}, // 298
    {299, nullptr}, // 299
    {300, nullptr}, // 300
    {301, nullptr}, // 301
    {-1, "%s krade %d zlat\375ch!"}, // 302
    {303, nullptr}, // 303
    {304, nullptr}, // 304
    {305, nullptr}, // 305
    {306, nullptr}, // 306
    {307, nullptr}, // 307
    {308, nullptr}, // 308
    {309, nullptr}, // 309
    {310, nullptr}, // 310
    {311, nullptr}, // 311
    {312, nullptr}, // 312
    {313, nullptr}, // 313
    {314, nullptr}, // 314
    {315, nullptr}, // 315
    {316, nullptr}, // 316
    {317, nullptr}, // 317
    {318, nullptr}, // 318
    {319, nullptr}, // 319
    {320, nullptr}, // 320
    {321, nullptr}, // 321
    {322, nullptr}, // 322
    {323, nullptr}, // 323
    {324, nullptr}, // 324
    {325, nullptr}, // 325
    {326, nullptr}, // 326
    {327, nullptr}, // 327
    {328, nullptr}, // 328
    {329, nullptr}, // 329
    {330, nullptr}, // 330
    {331, nullptr}, // 331
    {332, nullptr}, // 332
    {333, nullptr}, // 333
    {334, nullptr}, // 334
    {335, nullptr}, // 335
    {336, nullptr}, // 336
    {337, nullptr}, // 337
    {338, nullptr}, // 338
    {339, nullptr}, // 339
    {340, nullptr}, // 340
    {341, nullptr}, // 341
    {342, nullptr}, // 342
    {343, nullptr}, // 343
    {344, nullptr}, // 344
    {345, nullptr}, // 345
    {346, nullptr}, // 346
    {347, nullptr}, // 347
    {348, nullptr}, // 348
    {349, nullptr}, // 349
    {350, nullptr}, // 350
    {351, nullptr}, // 351
    {352, nullptr}, // 352
    {353, nullptr}, // 353
    {354, nullptr}, // 354
    {355, nullptr}, // 355
    {356, nullptr}, // 356
    {357, nullptr}, // 357
    {358, nullptr}, // 358
    {359, nullptr}, // 359
    {360, nullptr}, // 360
    {361, nullptr}, // 361
    {362, nullptr}, // 362
    {363, nullptr}, // 363
    {364, nullptr}, // 364
    {365, nullptr}, // 365
    {366, nullptr}, // 366
    {367, nullptr}, // 367
    {368, nullptr}, // 368
    {369, nullptr}, // 369
    {370, nullptr}, // 370
    {371, nullptr}, // 371
    {372, nullptr}, // 372
    {373, nullptr}, // 373
    {374, nullptr}, // 374
    {375, nullptr}, // 375
    {-1, "%s byl chycen p\370i kraden\355!"}, // 376
    {-1, "%s se nepovedlo nic ukr\341st!"}, // 377
    {-1, "%s %d, %d"}, // 378
    {-1, "Nen\341vid\354n\341"}, // 379
    {380, nullptr}, // 380
    {381, nullptr}, // 381
    {382, nullptr}, // 382
    {383, nullptr}, // 383
    {384, nullptr}, // 384
    {385, nullptr}, // 385
    {386, nullptr}, // 386
    {387, nullptr}, // 387
    {388, nullptr}, // 388
    {389, nullptr}, // 389
    {390, nullptr}, // 390
    {391, nullptr}, // 391
    {-1, "Nep\370\341telsk\341"}, // 392
    {393, nullptr}, // 393
    {394, nullptr}, // 394
    {395, nullptr}, // 395
    {396, nullptr}, // 396
    {397, nullptr}, // 397
    {398, nullptr}, // 398
    {-1, "Neutr\341ln\355"}, // 399
    {400, nullptr}, // 400
    {401, nullptr}, // 401
    {-1, "P\370\341telsk\341"}, // 402
    {403, nullptr}, // 403
    {404, nullptr}, // 404
    {405, nullptr}, // 405
    {406, nullptr}, // 406
    {407, nullptr}, // 407
    {408, nullptr}, // 408
    {409, nullptr}, // 409
    {410, nullptr}, // 410
    {411, nullptr}, // 411
    {412, nullptr}, // 412
    {413, nullptr}, // 413
    {414, nullptr}, // 414
    {415, nullptr}, // 415
    {416, nullptr}, // 416
    {417, nullptr}, // 417
    {418, nullptr}, // 418
    {419, nullptr}, // 419
    {420, nullptr}, // 420
    {421, nullptr}, // 421
    {422, nullptr}, // 422
    {423, nullptr}, // 423
    {424, nullptr}, // 424
    {425, nullptr}, // 425
    {426, nullptr}, // 426
    {427, nullptr}, // 427
    {428, nullptr}, // 428
    {429, nullptr}, // 429
    {430, nullptr}, // 430
    {431, nullptr}, // 431
    {432, nullptr}, // 432
    {433, nullptr}, // 433
    {-1, "Obl\355ben\341"}, // 434
    {435, nullptr}, // 435
    {436, nullptr}, // 436
    {437, nullptr}, // 437
    {438, nullptr}, // 438
    {439, nullptr}, // 439
    {440, nullptr}, // 440
    {441, nullptr}, // 441
    {442, nullptr}, // 442
    {443, nullptr}, // 443
    {444, nullptr}, // 444
    {445, nullptr}, // 445
    {446, nullptr}, // 446
    {447, nullptr}, // 447
    {448, nullptr}, // 448
    {449, nullptr}, // 449
    {450, nullptr}, // 450
    {451, nullptr}, // 451
    {452, nullptr}, // 452
    {453, nullptr}, // 453
    {454, nullptr}, // 454
    {455, nullptr}, // 455
    {456, nullptr}, // 456
    {457, nullptr}, // 457
    {458, nullptr}, // 458
    {459, nullptr}, // 459
    {460, nullptr}, // 460
    {461, nullptr}, // 461
    {462, nullptr}, // 462
    {463, nullptr}, // 463
    {464, nullptr}, // 464
    {465, nullptr}, // 465
    {466, nullptr}, // 466
    {467, nullptr}, // 467
    {468, nullptr}, // 468
    {469, nullptr}, // 469
    {470, nullptr}, // 470
    {471, nullptr}, // 471
    {472, nullptr}, // 472
    {473, nullptr}, // 473
    {474, nullptr}, // 474
    {475, nullptr}, // 475
    {476, nullptr}, // 476
    {477, nullptr}, // 477
    {478, nullptr}, // 478
    {479, nullptr}, // 479
    {480, nullptr}, // 480
    {481, nullptr}, // 481
    {482, nullptr}, // 482
    {483, nullptr}, // 483
    {484, nullptr}, // 484
    {485, nullptr}, // 485
    {486, nullptr}, // 486
    {487, nullptr}, // 487
    {488, nullptr}, // 488
    {489, nullptr}, // 489
    {490, nullptr}, // 490
    {491, nullptr}, // 491
    {492, nullptr}, // 492
    {493, nullptr}, // 493
    {494, nullptr}, // 494
    {495, nullptr}, // 495
    {496, nullptr}, // 496
    {497, nullptr}, // 497
    {-1, "Bylink\341\370"}, // 498
    {499, nullptr}, // 499
    {500, nullptr}, // 500
    {501, nullptr}, // 501
    {502, nullptr}, // 502
    {503, nullptr}, // 503
    {504, nullptr}, // 504
    {505, nullptr}, // 505
    {506, nullptr}, // 506
    {507, nullptr}, // 507
    {508, nullptr}, // 508
    {509, nullptr}, // 509
    {510, nullptr}, // 510
    {511, nullptr}, // 511
    {512, nullptr}, // 512
    {513, nullptr}, // 513
    {514, nullptr}, // 514
    {515, nullptr}, // 515
    {516, nullptr}, // 516
    {517, nullptr}, // 517
    {518, nullptr}, // 518
    {519, nullptr}, // 519
    {520, nullptr}, // 520
    {521, nullptr}, // 521
    {522, nullptr}, // 522
    {523, nullptr}, // 523
    {524, nullptr}, // 524
    {-1, "L\351k\341rn\355k"}, // 525
    {526, nullptr}, // 526
    {527, nullptr}, // 527
    {528, nullptr}, // 528
    {529, nullptr}, // 529
    {530, nullptr}, // 530
    {531, nullptr}, // 531
    {532, nullptr}, // 532
    {533, nullptr}, // 533
    {534, nullptr}, // 534
    {535, nullptr}, // 535
    {536, nullptr}, // 536
    {537, nullptr}, // 537
    {538, nullptr}, // 538
    {539, nullptr}, // 539
    {540, nullptr}, // 540
    {541, nullptr}, // 541
    {542, nullptr}, // 542
    {543, nullptr}, // 543
    {544, nullptr}, // 544
    {545, nullptr}, // 545
    {546, nullptr}, // 546
    {547, nullptr}, // 547
    {548, nullptr}, // 548
    {549, nullptr}, // 549
    {550, nullptr}, // 550
    {551, nullptr}, // 551
    {552, nullptr}, // 552
    {553, nullptr}, // 553
    {554, nullptr}, // 554
    {555, nullptr}, // 555
    {556, nullptr}, // 556
    {557, nullptr}, // 557
    {558, nullptr}, // 558
    {559, nullptr}, // 559
    {560, nullptr}, // 560
    {561, nullptr}, // 561
    {562, nullptr}, // 562
    {563, nullptr}, // 563
    {564, nullptr}, // 564
    {565, nullptr}, // 565
    {566, nullptr}, // 566
    {567, nullptr}, // 567
    {568, nullptr}, // 568
    {569, nullptr}, // 569
    {570, nullptr}, // 570
    {571, nullptr}, // 571
    {572, nullptr}, // 572
    {573, nullptr}, // 573
    {574, nullptr}, // 574
    {575, nullptr}, // 575
    {576, nullptr}, // 576
    {577, nullptr}, // 577
    {578, nullptr}, // 578
    {579, nullptr}, // 579
    {580, nullptr}, // 580
    {581, nullptr}, // 581
    {582, nullptr}, // 582
    {583, nullptr}, // 583
    {584, nullptr}, // 584
    {585, nullptr}, // 585
    {586, nullptr}, // 586
    {587, nullptr}, // 587
    {588, nullptr}, // 588
    {589, nullptr}, // 589
    {590, nullptr}, // 590
    {591, nullptr}, // 591
    {592, nullptr}, // 592
    {593, nullptr}, // 593
    {594, nullptr}, // 594
    {595, nullptr}, // 595
    {-1, "Kaplan"}, // 596
    {-1, "Diplomat"}, // 597
    {-1, "Kouzeln\355k"}, // 598
    {-1, "Prel\341t"}, // 599
    {-1, "Mudrc"}, // 600
    {-1, "Zombie"}, // 601
    {-1, "Historie"}, // 602
    {-1, "Zapla\235 pokutu"}, // 603
    {-1, "Lov odm\354n"}, // 604
    {-1, "Sou\350asn\341 pokuta"}, // 605
    {-1, "Zaplatit"}, // 606
    {-1, "Zotro\350en\375"}, // 607
    {-1, "Zb\354sil\375"}, // 608
    {-1, "Hodina moci"}, // 609
    {-1, "Den ochrany"}, // 610
    {-1, "Hr\341t Arcomage"}, // 611
    {-1, "Ulo\236ena hra je po\232kozen\341!  K\363d=%d"}, // 612
    {-1, "AutoSave.MM7"}, // 613
    {-1, "Nov\341 hra"}, // 614
    {-1, "Ulo\236it hru"}, // 615
    {-1, "Nahr\341t hru"}, // 616
    {-1, "Zvuk, kl\341vesnice, mo\236nosti nastaven\355\205"}, // 617
    {-1, "Konec"}, // 618
    {-1, "N\341vrat do hry"}, // 619
    {-1, "Pravidla"}, // 620
    {-1, "Hrajte"}, // 621
    {-1, "Podm\355nky v\355t\354zstv\355"}, // 622
    {-1, "Bonus"}, // 623
    {-1, "Fyzick\375"}, // 624
    {-1, "Imunn\355"}, // 625
    {181, nullptr}, // 626
    {-1, "Odoln\375"}, // 627
    {213, nullptr}, // 628
    {-1, "Kouzla"}, // 629
    {-1, "?"}, // 630
    {-1, "Efekty"}, // 631
    {-1, "Tuto \372rove\362 dovednosti se %s nem\371\236e nau\350it."}, // 632
    {-1, "Mus\355\232 b\375t pov\375\232en do hodnosti %s, aby ses nau\350il tuto \372rove\362 dovednosti."}, // 633
    {-1, "Mus\355\232 b\375t pov\375\232en do hodnosti %s nebo %s, aby ses nau\350il tuto \372rove\362 dovednosti."}, // 634
    {-1, "%s omra\350uje %s"}, // 635
    {-1, "%s ochromuje %s"}, // 636
    {-1, "%s se vyh\375b\341 zran\354n\355"}, // 637
    {-1, "Pobl\355\236 se nach\341zej\355 nep\370\341telsk\341 stvo\370en\355!"}, // 638
    {-1, "Rem\355za!"}, // 639
    {-1, "Zv\355t\354zili jste!"}, // 640
    {-1, "Prohr\341li jste!"}, // 641
    {-1, "Chyba"}, // 642
    {-1, "V\375hra postaven\355m v\354\236e!"}, // 643
    {-1, "Rem\355za postaven\355m stejn\375ch v\354\236\355!"}, // 644
    {-1, "V\375hra zni\350en\355m soupe\370ovy v\354\236e!"}, // 645
    {-1, "V\375hra nashrom\341\236d\354n\355m surovin!"}, // 646
    {-1, "Rem\355za nashrom\341\236d\354n\355m surovin z\341rove\362 s postaven\355m v\354\236e a zdi!"}, // 647
    {-1, "Tato postava u\236 nem\371\236e nikoho p\370ivolat!"}, // 648
    {-1, "P\370ivol\341n"}, // 649
    {-1, "Sou\350asn\351 zdrav\355"}, // 650
    {-1, "Vytvrzeno"}, // 651
    {-1, "Dokud jste pod vodou, nem\371\236ete tohle ud\354lat!"}, // 652
    {88, nullptr}, // 653
    {-1, "D\236b\341n prom\354ny hrdiny %s"}, // 654
    {-1, "D\236b\341n %s"}, // 655
    {-1, "Hra byla ulo\236ena!"}, // 656
    {-1, "D\375ch\341n\355 ve vod\354"}, // 657
    {-1, "Va\232e odm\354na"}, // 658
    {-1, "x: %d  y: %d"}, // 659
    {-1, "Top\355te se!"}, // 660
    {-1, "Ho\370\355te!"}, // 661
    {-1, "Instrukto\370i"}, // 662
    {-1, "Potrv\341 %d dn\355, ne\236 doraz\355te do zem\354 jm\351nem %s."}, // 663
    {-1, "Kliknut\355m sem ukon\350\355\232 tvorbu dru\236iny a za\350ne\232 hru."}, // 664
    {-1, "Tla\350\355tko Ok"}, // 665
    {-1, "Vyma\236 v\232echny statistiky a dovednosti dru\236iny."}, // 666
    {-1, "Tla\350\355tko Vyma\236"}, // 667
    {-1, "Uber"}, // 668
    {-1, "Ubere bod ze zv\375razn\354n\351 statistiky a p\370ipo\350te ho k polo\236ce bonus"}, // 669
    {-1, "P\370idej"}, // 670
    {-1, "P\370id\341 bod k zv\375razn\354n\351 statistice a ode\350te ho od polo\236ky bonus"}, // 671
    {-1, "Za va\232e nespo\350etn\351 zlo\350iny a nap\341chan\351 k\370ivdy jste byli na jeden rok vsazeni do \236al\341\370e."}, // 672
    {-1, "Dosud jste nezaplatili pokutu \350\355taj\355c\355 %lu zlat\375ch. Zaplat\355te pokutu nebo p\371jdete na jeden rok do \236al\341\370e?"}, // 673
    {-1, "Do\350asn\354 S\355la"}, // 674
    {-1, "Skv\354l\341 pr\341ce! Po aktivaci Br\341ny v\341m le\236\355 u nohou tis\355ce sv\354t\371. Snad v n\354kter\351m z "
        "nich naleznete samotn\351 Prad\341vn\351 a vr\341t\355te se s plody jejich mocn\351 civilizace, kter\351 v\354nuj\355 "
        "va\232emu sv\354tu a va\232emu kr\341lovstv\355."}, // 675
    {-1, "Skv\354l\351! Dokon\350en\341 Nebesk\341 v\375he\362 opat\370ila dostatek blaster\371 a te\357 nic nestoj\355 v "
        "cest\354 va\232im pl\341n\371m. Brzo v\341m bude cel\375 sv\354t le\236et u nohou! Ned\341 v\341m v\232ak pokoj "
        "my\232lenka, co bylo za Br\341nou, kterou se sna\236ila za ka\236dou cenu zprovoznit druh\341 strana."}, // 676
}};
