"""Generates OpenEnroth/src/Engine/Mm6LstrTable.h, the MM7 -> MM6 global.txt index table.

Inputs are the English MM6 and MM7 global.txt files from https://github.com/might-and-magic/mm678-i18n
(source/en/mm6/data/10LocLANG.icons/GLOBAL.TXT and source/en/mm7/DATA/10LocLANG.events/Global.txt),
stored in reference/i18n/ as mm6-global-en.txt and mm7-global-en.txt.
MM7 strings that MM6 doesn't have get their text from the Czech MM7 global.txt (reference/i18n/mm7-global-cs.txt, taken
from the Czech MM7 Events.lod) as a fallback, or the English one where the Czech file doesn't have it. The Czech text
stays in cp1250 like the game data, written as octal escapes.
"""
import pathlib
import re

root = pathlib.Path(__file__).resolve().parent.parent


def load(name, encoding='cp1252'):
    result = {}
    for line in (root / 'reference/i18n' / name).read_text(encoding=encoding, errors='replace').splitlines()[2:]:
        tokens = line.split('\t')
        if tokens[0].strip().isdigit():
            text = tokens[1] if len(tokens) > 1 else ''
            if len(text) >= 2 and text[0] == '"' and text[-1] == '"':
                text = text[1:-1].replace('""', '"')
            result[int(tokens[0])] = text
    return result


def norm(s):
    return re.sub(r'[^a-z0-9%]+', '', s.lower())


def cpp(s, encoding='ascii'):
    out = ''
    for ch in s:
        if ch in '\\"':
            out += '\\' + ch
        elif ord(ch) < 128:
            out += ch
        else:
            out += ''.join(f'\\{b:03o}' for b in ch.encode(encoding))
    return '"' + out + '"'


mm6 = load('mm6-global-en.txt')
mm7 = load('mm7-global-en.txt')
mm7cs = load('mm7-global-cs.txt', 'cp1250')
index6 = {}
for i, s in sorted(mm6.items()):
    index6.setdefault(norm(s), []).append(i)

# MM7 strings that say the same as a differently worded MM6 string.
overrides = {
    30: 30,    # "Bonus" / "Bonus Pts"
    62: 62, 63: 63, 118: 118, 157: 157, 167: 167, 176: 176,  # "Might and Magic VII" / "VI" messages.
    186: 525,  # "Time in Erathia" / "Time in Enroth"
    412: 412,  # "Create Party cannot be completed..." / "Create Character can not be completed..."
    489: 489,  # "You have %d total gold, %d in the Bank" / "You have %d gold, %d in the Bank"
    574: 574, 577: 577,
    134: 539,  # "Buy Standard" / "Nákup"
    152: 543,  # "Buy Special" / "Speciální předměty"
    159: 120,  # "Display Inventory" / "Inventář"
    160: 535,  # "Learn Skills" / "Naučit se"
    177: 33,   # "Standard" / "Koupit", the shop menu entry that opens the standard wares.
}

rows = []
for i in range(max(mm7) + 1):
    s = mm7.get(i, '')
    n = norm(s)
    if i in overrides:
        rows.append((overrides[i], 'nullptr'))
    elif i in mm6 and norm(mm6[i]) == n:
        rows.append((i, 'nullptr'))
    elif n and len(index6.get(n, [])) == 1:
        rows.append((index6[n][0], 'nullptr'))
    elif mm7cs.get(i):
        rows.append((-1, cpp(mm7cs[i], 'cp1250')))
    else:
        rows.append((-1, cpp(s)))

out = ['#pragma once', '', '// Generated by MaM 6/tools/gen_mm6_lstr.py, do not edit.', '', '#include <array>', '',
       '/**', ' * MM6 global.txt index for each MM7 `LstrId`, or -1 with a fallback text if MM6 has no such string. Fallbacks are',
       ' * the Czech MM7 texts in cp1250.',
       ' */', 'struct Mm6LstrEntry {', '    int mm6Index;', '    const char *fallback;', '};', '',
       f'inline constexpr std::array<Mm6LstrEntry, {len(rows)}> mm6LstrTable = {{{{']
def entry_lines(index, fallback, i):
    line = f'    {{{index}, {fallback}}}, // {i}'
    if len(line) <= 200 or not fallback.startswith('"'):
        return [line]
    body, parts = fallback[1:-1], []
    while body:
        cut = min(len(body), 120)
        if cut < len(body) and body.rfind(' ', 0, cut) > 60:
            cut = body.rfind(' ', 0, cut) + 1
        # Never split an escape sequence, octal escapes are a backslash and three digits.
        while cut < len(body) and any(body[k] == '\\' and k + (4 if body[k + 1:k + 2].isdigit() else 2) > cut
                                      for k in range(max(0, cut - 4), cut)):
            cut -= 1
        parts.append(body[:cut])
        body = body[cut:]
    lines = [f'    {{{index}, "{parts[0]}"'] + [f'        "{p}"' for p in parts[1:]]
    lines[-1] += f'}}, // {i}'
    return lines


for i, (index, fallback) in enumerate(rows):
    out += entry_lines(index, fallback, i)
out += ['}};', '']
(root / 'OpenEnroth/src/Engine/Mm6LstrTable.h').write_text('\n'.join(out), encoding='utf-8', newline='\n')
print(len(rows), sum(1 for r in rows if r[0] < 0))
